Update dependencies.
`rustsec-0.31.0` is unable to parse CVSS 4.0, thus throws an error
on the current advisory database:

```
Error: failed to read fetched advisory-db repo
Caused by:
    parse error: error parsing [...]/advisory-db/crates/cap-primitives/RUSTSEC-2024-0445.md: parse error: TOML parse error at line 8, column 8
      |
    8 | cvss = "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
      |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    unsupported CVSS version: 4.0
```

Updating to `rustsec-0.31.0` fixes the issue.

Fixes: dcoles/gitlab-cargo-audit#17